theme: jekyll-theme-architect
title: Tomer Markovich
description:  Blavatnik Postdoctoral Fellow 
Group of Prof. Michael E. Cates 

DAMTP, Centre for Mathematical Sciences 
University of Cambridge 
Wilberforce Road 
CB3 0WA, United Kingdom 

+44 (0)1223 760453
tm598@damtp.cam.ac.uk
